"""
The page-side half of a demo: fitting an app into a page that embeds it.

A compiled demo is served in an ``<iframe>``, and the embedding page has to
decide how wide and how tall to make it. That is not boilerplate anyone should
write twice, because two of the answers are counter-intuitive and one of them
is a bug you cannot see on a desktop:

* **The frame must not be ``width: 100%``.** Every browser on an iPad is
  WebKit underneath -- Firefox and Chrome there are skins on Safari's engine --
  and WebKit sizes an iframe to its CONTENT rather than honouring a percentage
  width. Against a Panel app in ``stretch_width``, that is a feedback loop with
  no fixed point: the app is as wide as the frame, the frame is as wide as the
  app, and the pair runs off the side of the page. ``width: 1px`` with
  ``min-width: 100%`` says "the width available, and no more", which WebKit
  does honour. Every desktop engine pins the frame and hides the problem, so
  this reaches a reader on a tablet before it reaches the person who built it.

* **Above the design width, SCALE rather than stretch.** If the frame merely
  fills the width, every element keeps its intrinsic size: the plot grows
  without limit while 16 px text and 18 px slider handles stay put, and on a
  wide screen the controls end up small and fiddly beside the model. Zooming
  the frame enlarges everything together, the way zooming a PDF does.

* **No fixed height can work**, because the plot's height follows the reader's
  window. The frame is measured -- after being collapsed, since Panel's layout
  fills whatever height it is given and a tall frame just reports back the
  height it was last set.

:func:`write_embed_script` emits this as a single ``artesian-embed.js`` next to
the compiled app, shared by every demo in the directory the way the panel and
bokeh wheels are. A page then needs an iframe and a script tag, and inherits
every fix made here afterwards.
"""

import ast
import glob
import os
import re

#: Emitted next to the compiled app, and shared by every demo in that
#: directory. The name is fixed so a page can reference it without knowing
#: which app it sits beside.
EMBED_FILENAME = "artesian-embed.js"

#: Marks an iframe as one to manage. An attribute rather than a class, so it
#: cannot collide with a site's styling.
EMBED_ATTRIBUTE = "data-artesian"

#: Where the design width is recorded in a compiled page, so that the app --
#: not the embedding page -- is the single source of truth for it.
DESIGN_WIDTH_META = "artesian-design-width"

#: Emitted alongside the script, and linked from the page's head.
EMBED_CSS_FILENAME = "artesian-embed.css"

#: The static half, and it is not optional. The script cannot size the frame
#: until the frame's DOCUMENT is reachable, and for a page that pulls tens of
#: megabytes of Pyodide that is many seconds. Whatever the frame looks like in
#: the meantime is what the reader sits and stares at. With no CSS that is the
#: browser's default iframe -- about 300 px wide -- stretched to whatever
#: `height` the page gave it: a narrow, tall box with the demo squeezed into a
#: column and blank space beneath, which reads as "stuck loading". It was
#: shipped that way and reported as exactly that.
#:
#: `width: 1px` with `min-width: 100%` rather than `width: 100%`, for the same
#: reason the script uses it: WebKit -- every browser on an iPad -- sizes an
#: iframe to its content rather than honouring a percentage width. This form
#: is correct with no JavaScript at all, which is the point of putting it in a
#: stylesheet instead of leaving the script to set it.
EMBED_CSS = """\
/* artesian-embed.css -- how a compiled artesian demo sits in a page.
 *
 * Generated by artesian. Do not edit this file; edit artesian/embed.py.
 *
 * Link this from the page HEAD. It must apply before any script runs: the
 * sizing script cannot measure a frame whose document has not loaded, and on
 * a slow connection that is the reader's whole first impression.
 */
iframe[{attribute}] {
  border: 0;
  display: block;
  /* NOT width: 100%. WebKit sizes an iframe to its content rather than
     honouring a percentage, and a stretch-to-fit app then grows with it off
     the side of the page. min-width is honoured where width is not. */
  width: 1px;
  min-width: 100%;
}
""".replace("{attribute}", EMBED_ATTRIBUTE)

EMBED_TEMPLATE = """\
/* artesian-embed.js -- fit compiled artesian demos into the page.
 *
 * Generated by artesian. Do not edit this file; edit artesian/embed.py.
 *
 * Manages every <iframe {attribute}> on the page: sizes it to its content,
 * and above the app's design width scales the whole app rather than stretching
 * it. The design width is read from the compiled app itself (a
 * <meta name="{meta}">), so the page never repeats it; a
 * data-design-width attribute on the iframe overrides, and with neither the
 * frame is fitted but never scaled.
 */
(function () {
  'use strict';

  // When to re-measure after a frame loads, in milliseconds. Not a poll: the
  // ResizeObserver does the work, and these only catch an update it dropped.
  var RETRIES = [250, 1000, 3000, 10000, 30000];

  function document_of(frame) {
    try {
      return frame.contentDocument || frame.contentWindow.document;
    } catch (e) {
      return null;                 // different origin: leave everything alone
    }
  }

  function design_width(frame) {
    // THE ATTRIBUTE FIRST, and that ordering is the whole point. Reading the
    // width out of the compiled page keeps the number in one place, which is
    // tidy, but it requires the frame's document to be readable at the moment
    // the page lays itself out -- and it is not. An iframe starts on a blank
    // document; on WebKit, which is every browser on an iPad, that is what a
    // page script sees. No meta tag, no design width, and a demo that is never
    // scaled: it sits at its own layout width inside a wider frame with blank
    // space around it.
    //
    // This is not hypothetical. Both GeomorphOnline exercises worked on an
    // iPad while each page hardcoded its own design width, and broke in the
    // commit that replaced that with reading the meta tag.
    var attr = parseFloat(frame.getAttribute('data-design-width'));
    if (attr > 0) { return attr; }
    var doc = document_of(frame);
    if (doc) {
      var meta = doc.querySelector('meta[name="{meta}"]');
      if (meta) {
        var declared = parseFloat(meta.getAttribute('content'));
        if (declared > 0) { return declared; }
      }
    }
    return 0;                      // 0 : fit, but never scale
  }

  function available_width(frame) {
    // Measure the PARENT, never the frame. Once the frame is zoomed, its own
    // clientWidth is reported in its local coordinates -- it would read back
    // the design width, give a factor of 1, and oscillate. The parent is not
    // zoomed, so its width is the honest one.
    var host = frame.parentElement;
    if (!host || !host.clientWidth) {
      return frame.getBoundingClientRect().width;
    }
    // clientWidth INCLUDES the parent's padding, and the frame lives in the
    // content box. Scaling to the padded width overflows the column by
    // exactly the padding -- invisible in a container that has none, which is
    // why this survived two deployments and only showed up on a test page
    // with 16 px of it.
    var style = window.getComputedStyle(host);
    var pad = (parseFloat(style.paddingLeft) || 0)
            + (parseFloat(style.paddingRight) || 0);
    return Math.max(host.clientWidth - pad, 0);
  }

  function manage(frame) {
    var adjusting = false;
    var observer = null;
    var observed = null;           // the document the observer is attached to

    function attach() {
      // An iframe does not start empty: it starts with a BLANK document, whose
      // readyState is already 'complete'. Observing that one attaches to a body
      // that is about to be thrown away and will never resize again, and
      // reading the design width from it finds no meta tag -- so the demo is
      // never scaled and the height is whatever the blank document had. That
      // is what an iPad showed, and no desktop engine did, because there the
      // real document arrives before the script looks.
      //
      // So the observer follows the CURRENT document, and re-attaches whenever
      // it changes.
      if (typeof ResizeObserver === 'undefined') { return; }
      var doc = document_of(frame);
      if (!doc || !doc.body || doc === observed) { return; }
      if (observer) { observer.disconnect(); }
      observer = new ResizeObserver(fit);
      observer.observe(doc.body);
      observed = doc;
    }

    function fit() {
      attach();                    // the document may have been replaced
      if (adjusting) { return; }   // ignore the events our own writes cause
      var doc = document_of(frame);
      if (!doc || !doc.body) { return; }

      adjusting = true;

      var design = design_width(frame);
      var available = available_width(frame);
      // Below the design width, stay at 1 and let the app lay itself out
      // responsively -- a phone should reflow, not render a shrunken page.
      var factor = (design && available > design) ? available / design : 1;

      if (factor === 1) {
        frame.style.zoom = '';
        // NOT width: 100%. WebKit -- which is every browser on an iPad --
        // sizes an iframe to its content rather than honouring a percentage,
        // and a stretch-to-fit app then grows with it off the side of the
        // page. min-width is honoured where width: 100% is not.
        frame.style.width = '1px';
        frame.style.minWidth = '100%';
      } else {
        // Zoom the frame itself, not its contents. `zoom` scales layout as
        // well as paint, so the frame's interior measures the design width
        // across and the plot re-renders at full resolution rather than being
        // upscaled and blurred.
        frame.style.zoom = factor;
        // An explicit pixel width in the frame's own coordinates: a percentage
        // would resolve against the parent and then be scaled by the zoom,
        // overflowing the page.
        frame.style.width = design + 'px';
        frame.style.minWidth = '0';       // or the min-width above wins
      }

      var previous = frame.style.height;
      // Collapse before measuring: Panel's layout fills whatever height it is
      // given, so measuring a tall frame reports back the height we last set.
      // Adding padding to the measurement makes it grow on every callback.
      frame.style.height = '0px';
      var height = Math.max(doc.body.scrollHeight,
                            doc.documentElement.scrollHeight);
      frame.style.height = height > 0 ? Math.ceil(height) + 'px'
                                      : (previous || '600px');

      if (typeof requestAnimationFrame === 'function') {
        requestAnimationFrame(function () { adjusting = false; });
      } else {
        setTimeout(function () { adjusting = false; }, 0);
      }
    }

    function watch() {
      // Panel renders asynchronously, and the first render waits on Pyodide
      // downloading -- tens of seconds. Watch the body rather than measure
      // once; fit() attaches to whichever document is current.
      fit();
      // And re-measure a few times anyway. `adjusting` suppresses the observer
      // callbacks our own writes cause, but it cannot tell those from a real
      // one arriving in the same moment, so a render that lands inside that
      // window is dropped and the frame keeps whatever height it had when the
      // app was still laying itself out -- blank space under the demo, on a
      // machine fast enough to hit it. A few later measurements cost nothing
      // and make that self-correcting rather than permanent.
      for (var i = 0; i < RETRIES.length; i++) {
        setTimeout(fit, RETRIES[i]);
      }
    }

    frame.style.border = frame.style.border || 'none';
    frame.style.display = 'block';
    frame.addEventListener('load', watch);
    window.addEventListener('resize', fit);
    var doc = document_of(frame);
    if (doc && doc.readyState === 'complete') {
      watch();                     // already loaded from cache
    }
  }

  function start() {
    var frames = document.querySelectorAll('iframe[{attribute}]');
    for (var i = 0; i < frames.length; i++) { manage(frames[i]); }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
"""

#: The script as emitted. Built by substitution rather than %-formatting: the
#: JavaScript is full of literal per-cent signs (``100%``), and a format string
#: would have to escape every one of them.
EMBED_JS = (EMBED_TEMPLATE
            .replace("{attribute}", EMBED_ATTRIBUTE)
            .replace("{meta}", DESIGN_WIDTH_META))


def write_embed_script(outdir):
    """Write the embed script and stylesheet into ``outdir``.

    Returns ``(script_path, css_path)``. Both are rewritten on every build, so
    a demo directory always carries the pair matching the artesian that
    produced it, and both are shared by every app in the directory -- which is
    the point of emitting them rather than leaving each page to copy them.

    Two files rather than one because they run at different times. The
    stylesheet decides what the frame looks like from the moment it is parsed;
    the script cannot do anything until the frame's document has loaded, which
    on a demo pulling tens of megabytes of Pyodide is many seconds later.
    """
    script = os.path.join(outdir, EMBED_FILENAME)
    with open(script, "w", encoding="utf-8") as fh:
        fh.write(EMBED_JS)
    css = os.path.join(outdir, EMBED_CSS_FILENAME)
    with open(css, "w", encoding="utf-8") as fh:
        fh.write(EMBED_CSS)
    return script, css


def declared_design_width(app):
    """The ``DESIGN_WIDTH`` a Panel app declares, or ``None``.

    Read by parsing the source, not by importing it: the build already runs
    the app once through ``panel convert``, and a second execution to read one
    constant would be both slow and a second chance for a side effect.

    Reading it from the app at all is what keeps the number in ONE place. The
    app needs it anyway -- it is the width it lays itself out for, and what it
    should cap its own layout at -- and the embedding page needs to know the
    same number to decide when to scale. Left to a human to keep those in step,
    they drift.
    """
    try:
        with open(app, encoding="utf-8") as fh:
            tree = ast.parse(fh.read())
    except (OSError, SyntaxError):
        return None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "DESIGN_WIDTH":
                value = node.value
                if isinstance(value, ast.Constant) and \
                        isinstance(value.value, (int, float)) and \
                        value.value > 0:
                    return value.value
    return None


def inject_design_width(page, width):
    """Record ``width`` in the compiled ``page`` as a meta tag.

    The embedding page reads it from here, through the iframe, so the app
    stays the single source of truth for the width it was laid out at.
    Replaces any tag a previous build left, rather than accumulating them.
    """
    with open(page, encoding="utf-8") as fh:
        text = fh.read()

    tag = '<meta name="%s" content="%s">' % (DESIGN_WIDTH_META, int(width))
    existing = re.compile(
        r'<meta\s+name="%s"[^>]*>' % re.escape(DESIGN_WIDTH_META))
    if existing.search(text):
        text = existing.sub(tag, text)
    elif "<head>" in text:
        text = text.replace("<head>", "<head>\n  " + tag, 1)
    else:
        return False

    with open(page, "w", encoding="utf-8") as fh:
        fh.write(text)
    return True


def page_design_width(page):
    """The design width recorded in a compiled ``page``, or 0 if it has none.

    The inverse of :func:`inject_design_width`, and the same question the
    embedding script asks at run time.
    """
    try:
        with open(page, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return 0
    found = re.search(
        r'<meta\s+name="%s"\s+content="([0-9.]+)"' % re.escape(DESIGN_WIDTH_META),
        text)
    return float(found.group(1)) if found else 0


def unscaled_pages(outdir, exclude=()):
    """Compiled pages in ``outdir`` that record no design width.

    Such a page is still served and still fits its frame, but the embedding
    script has nothing to scale it by, so its text and controls keep their
    size while its plot grows. Nothing about it looks broken, which is why it
    is worth reporting: the failure is a demo that is merely worse, on a page
    that loads perfectly.

    Apps built before artesian recorded the width at all land here, which is
    the common case -- a directory shared by several demos, only some of them
    rebuilt since.
    """
    skip = {os.path.abspath(p) for p in exclude}
    stale = []
    for page in sorted(glob.glob(os.path.join(outdir, "*.html"))):
        if os.path.abspath(page) in skip:
            continue
        if os.path.basename(page) == "index.html":
            continue
        if not page_design_width(page):
            stale.append(os.path.basename(page))
    return stale
