"""
The page-side half of a demo: fitting an app into a page that embeds it.

A compiled demo is served in an ``<iframe>``, and the embedding page has to
decide how wide and how tall to make it. That is not boilerplate anyone should
write twice, because two of the answers are counter-intuitive and one of them
is a bug you cannot see on a desktop:

* **The frame must not be ``width: 100%``.** Every browser on an iPad is
  WebKit underneath -- Firefox and Chrome there are skins on Safari's engine --
  and WebKit sizes an iframe to its CONTENT rather than honouring a percentage
  width. Against a Panel app in ``stretch_width``, that is a feedback loop with
  no fixed point: the app is as wide as the frame, the frame is as wide as the
  app, and the pair runs off the side of the page. ``width: 1px`` with
  ``min-width: 100%`` says "the width available, and no more", which WebKit
  does honour. Every desktop engine pins the frame and hides the problem, so
  this reaches a reader on a tablet before it reaches the person who built it.

* **Above the design width, SCALE rather than stretch.** If the frame merely
  fills the width, every element keeps its intrinsic size: the plot grows
  without limit while 16 px text and 18 px slider handles stay put, and on a
  wide screen the controls end up small and fiddly beside the model. Zooming
  the frame enlarges everything together, the way zooming a PDF does.

* **No fixed height can work**, because the plot's height follows the reader's
  window. The frame is measured -- after being collapsed, since Panel's layout
  fills whatever height it is given and a tall frame just reports back the
  height it was last set.

:func:`write_embed_script` emits this as a single ``artesian-embed.js`` next to
the compiled app, shared by every demo in the directory the way the panel and
bokeh wheels are. A page then needs an iframe and a script tag, and inherits
every fix made here afterwards.
"""

import ast
import os
import re

#: Emitted next to the compiled app, and shared by every demo in that
#: directory. The name is fixed so a page can reference it without knowing
#: which app it sits beside.
EMBED_FILENAME = "artesian-embed.js"

#: Marks an iframe as one to manage. An attribute rather than a class, so it
#: cannot collide with a site's styling.
EMBED_ATTRIBUTE = "data-artesian"

#: Where the design width is recorded in a compiled page, so that the app --
#: not the embedding page -- is the single source of truth for it.
DESIGN_WIDTH_META = "artesian-design-width"

EMBED_TEMPLATE = """\
/* artesian-embed.js -- fit compiled artesian demos into the page.
 *
 * Generated by artesian. Do not edit this file; edit artesian/embed.py.
 *
 * Manages every <iframe {attribute}> on the page: sizes it to its content,
 * and above the app's design width scales the whole app rather than stretching
 * it. The design width is read from the compiled app itself (a
 * <meta name="{meta}">), so the page never repeats it; a
 * data-design-width attribute on the iframe overrides, and with neither the
 * frame is fitted but never scaled.
 */
(function () {
  'use strict';

  function document_of(frame) {
    try {
      return frame.contentDocument || frame.contentWindow.document;
    } catch (e) {
      return null;                 // different origin: leave everything alone
    }
  }

  function design_width(frame) {
    var doc = document_of(frame);
    if (doc) {
      var meta = doc.querySelector('meta[name="{meta}"]');
      if (meta) {
        var declared = parseFloat(meta.getAttribute('content'));
        if (declared > 0) { return declared; }
      }
    }
    var attr = parseFloat(frame.getAttribute('data-design-width'));
    return attr > 0 ? attr : 0;    // 0 : fit, but never scale
  }

  function available_width(frame) {
    // Measure the PARENT, never the frame. Once the frame is zoomed, its own
    // clientWidth is reported in its local coordinates -- it would read back
    // the design width, give a factor of 1, and oscillate. The parent is not
    // zoomed, so its width is the honest one.
    var host = frame.parentElement;
    if (!host || !host.clientWidth) {
      return frame.getBoundingClientRect().width;
    }
    // clientWidth INCLUDES the parent's padding, and the frame lives in the
    // content box. Scaling to the padded width overflows the column by
    // exactly the padding -- invisible in a container that has none, which is
    // why this survived two deployments and only showed up on a test page
    // with 16 px of it.
    var style = window.getComputedStyle(host);
    var pad = (parseFloat(style.paddingLeft) || 0)
            + (parseFloat(style.paddingRight) || 0);
    return Math.max(host.clientWidth - pad, 0);
  }

  function manage(frame) {
    var adjusting = false;
    var observer = null;

    function fit() {
      if (adjusting) { return; }   // ignore the events our own writes cause
      var doc = document_of(frame);
      if (!doc || !doc.body) { return; }

      adjusting = true;

      var design = design_width(frame);
      var available = available_width(frame);
      // Below the design width, stay at 1 and let the app lay itself out
      // responsively -- a phone should reflow, not render a shrunken page.
      var factor = (design && available > design) ? available / design : 1;

      if (factor === 1) {
        frame.style.zoom = '';
        // NOT width: 100%. WebKit -- which is every browser on an iPad --
        // sizes an iframe to its content rather than honouring a percentage,
        // and a stretch-to-fit app then grows with it off the side of the
        // page. min-width is honoured where width: 100% is not.
        frame.style.width = '1px';
        frame.style.minWidth = '100%';
      } else {
        // Zoom the frame itself, not its contents. `zoom` scales layout as
        // well as paint, so the frame's interior measures the design width
        // across and the plot re-renders at full resolution rather than being
        // upscaled and blurred.
        frame.style.zoom = factor;
        // An explicit pixel width in the frame's own coordinates: a percentage
        // would resolve against the parent and then be scaled by the zoom,
        // overflowing the page.
        frame.style.width = design + 'px';
        frame.style.minWidth = '0';       // or the min-width above wins
      }

      var previous = frame.style.height;
      // Collapse before measuring: Panel's layout fills whatever height it is
      // given, so measuring a tall frame reports back the height we last set.
      // Adding padding to the measurement makes it grow on every callback.
      frame.style.height = '0px';
      var height = Math.max(doc.body.scrollHeight,
                            doc.documentElement.scrollHeight);
      frame.style.height = height > 0 ? Math.ceil(height) + 'px'
                                      : (previous || '600px');

      if (typeof requestAnimationFrame === 'function') {
        requestAnimationFrame(function () { adjusting = false; });
      } else {
        setTimeout(function () { adjusting = false; }, 0);
      }
    }

    function watch() {
      fit();
      // Panel renders asynchronously, and the first render waits on Pyodide
      // downloading -- tens of seconds. Watch the body rather than measure
      // once.
      if (typeof ResizeObserver === 'undefined') { return; }
      var doc = document_of(frame);
      if (!doc || !doc.body) { return; }
      if (observer) { observer.disconnect(); }
      observer = new ResizeObserver(fit);
      observer.observe(doc.body);
    }

    frame.style.border = frame.style.border || 'none';
    frame.style.display = 'block';
    frame.addEventListener('load', watch);
    window.addEventListener('resize', fit);
    var doc = document_of(frame);
    if (doc && doc.readyState === 'complete') {
      watch();                     // already loaded from cache
    }
  }

  function start() {
    var frames = document.querySelectorAll('iframe[{attribute}]');
    for (var i = 0; i < frames.length; i++) { manage(frames[i]); }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start);
  } else {
    start();
  }
})();
"""

#: The script as emitted. Built by substitution rather than %-formatting: the
#: JavaScript is full of literal per-cent signs (``100%``), and a format string
#: would have to escape every one of them.
EMBED_JS = (EMBED_TEMPLATE
            .replace("{attribute}", EMBED_ATTRIBUTE)
            .replace("{meta}", DESIGN_WIDTH_META))


def write_embed_script(outdir):
    """Write :data:`EMBED_FILENAME` into ``outdir`` and return its path.

    Rewritten on every build, so a demo directory always carries the embed
    script matching the artesian that produced it. It is shared by every app in
    the directory, so rewriting it updates them all at once -- which is the
    point of emitting it rather than leaving each page to copy it.
    """
    path = os.path.join(outdir, EMBED_FILENAME)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(EMBED_JS)
    return path


def declared_design_width(app):
    """The ``DESIGN_WIDTH`` a Panel app declares, or ``None``.

    Read by parsing the source, not by importing it: the build already runs
    the app once through ``panel convert``, and a second execution to read one
    constant would be both slow and a second chance for a side effect.

    Reading it from the app at all is what keeps the number in ONE place. The
    app needs it anyway -- it is the width it lays itself out for, and what it
    should cap its own layout at -- and the embedding page needs to know the
    same number to decide when to scale. Left to a human to keep those in step,
    they drift.
    """
    try:
        with open(app, encoding="utf-8") as fh:
            tree = ast.parse(fh.read())
    except (OSError, SyntaxError):
        return None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "DESIGN_WIDTH":
                value = node.value
                if isinstance(value, ast.Constant) and \
                        isinstance(value.value, (int, float)) and \
                        value.value > 0:
                    return value.value
    return None


def inject_design_width(page, width):
    """Record ``width`` in the compiled ``page`` as a meta tag.

    The embedding page reads it from here, through the iframe, so the app
    stays the single source of truth for the width it was laid out at.
    Replaces any tag a previous build left, rather than accumulating them.
    """
    with open(page, encoding="utf-8") as fh:
        text = fh.read()

    tag = '<meta name="%s" content="%s">' % (DESIGN_WIDTH_META, int(width))
    existing = re.compile(
        r'<meta\s+name="%s"[^>]*>' % re.escape(DESIGN_WIDTH_META))
    if existing.search(text):
        text = existing.sub(tag, text)
    elif "<head>" in text:
        text = text.replace("<head>", "<head>\n  " + tag, 1)
    else:
        return False

    with open(page, "w", encoding="utf-8") as fh:
        fh.write(text)
    return True
